---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rikimaul/repositories/refiutami.github.io
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
